def encoder(msgg):
        #print(msgg[0])
        fi=0
        se=1
        th=2
        leng=len(msgg)-1
        row1=list()
        while(fi<=leng):
            row1.append(msgg[fi])
            fi=fi+4
        while(se<=leng):
            row1.append(msgg[se])
            se=se+2
            if(se>leng):
                continue
            else:
                row1.append(msgg[se])
                se=se+2
        while(th<=leng):
            row1.append(msgg[th])
            th=th+4
        return(row1)
